name: Java CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Archive JAR
      run: mkdir output && cp target/demo-0.0.1-SNAPSHOT.jar output/

    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: demo-app
        path: output/demo-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: demo-app

    - name: Deploy (Example EC2 via SCP)
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 400 key.pem
        scp -i key.pem demo-0.0.1-SNAPSHOT.jar ec2-user@<EC2_PUBLIC_IP>:/home/ec2-user/demo.jar
        ssh -i key.pem ec2-user@<EC2_PUBLIC_IP> 'nohup java -jar demo.jar > output.log 2>&1 &'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
